import { Poppins } from "next/font/google";
import "./globals.css";
import { NextThemeProvider } from "@/lib/next-theme-provider";
import { ClerkProvider } from "@clerk/nextjs";

const poppins = Poppins({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
        <html lang="en">
      <body className={poppins.className}>
       <NextThemeProvider>
       {children}
       </NextThemeProvider>
        </body>
    </html>
    </ClerkProvider>
  );
}
